baseURL: https://pooriaazami.github.io/
locale: en-us
build:
  writeStats: true
title: Pooria Azami
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  author: Pooria Azami
  description: homepage
  copyright: powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: publications
    - item: education
    # - item: experiences
    # - item: projects
    # - item: skills
      # panel_id: skill-panel
    # - item: hobbies
